# Generated by Django 3.0.6 on 2020-05-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentoffer',
            options={'verbose_name': 'Recruitment Offer', 'verbose_name_plural': 'Recruitment Offers'},
        ),
        migrations.RenameField(
            model_name='recruitmentoffer',
            old_name='recruitment',
            new_name='recruiting_company',
        ),
        migrations.AlterField(
            model_name='recruitmentoffer',
            name='recruitment_salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
