# Generated by Django 3.0.6 on 2020-05-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20200517_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentoffer',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Subcategory'),
        ),
        migrations.AlterField(
            model_name='recruitmentoffer',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Category'),
        ),
    ]
